FROM oven/bun:1.2.19-alpine
WORKDIR /app

# Copie le code du mock
COPY . .

# Déplacer le répertoire de travail dans le sous-dossier `dev-mocks`
WORKDIR /app/dev-mocks

# Installe les deps (gelées si un lockfile est présent)
RUN bun install --frozen-lockfile

# Revenir au répertoire racine de l'application
WORKDIR /app

ENV WS_PORT=3002
ENV PORT=3002
EXPOSE 3002

# Bun exécute TypeScript nativement
CMD ["bun", "dev-mocks/mock-ws-server.ts"]
