version: "3.9"

services:
  # Shell (host)
  shell:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
      target: ng-runtime
      args:
        PROJECT: shell
        CONFIG: development-docker
    image: ycyw/shell:dev-docker
    environment:
      - APP_BACKOFFICE_URL=http://localhost:4201/remoteEntry.json
      - APP_RESERVATION_URL=http://localhost:4202/remoteEntry.json
      - APP_SUPPORT_URL=http://localhost:4203/remoteEntry.json
      - GATEWAY_URL=http://localhost:8080
      - GATEWAY_WS=ws://localhost:8080
    ports:
      - "4200:80"

  # Backoffice
  app-backoffice:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
      target: ng-runtime
      args:
        PROJECT: app-backoffice
        CONFIG: development-docker
    image: ycyw/app-backoffice:dev-docker
    environment:
      - APP_SUPPORT_URL=http://localhost:4203/remoteEntry.json
      - GATEWAY_URL=http://localhost:8080
    ports:
      - "4201:80"

        # Reservation
  app-reservation:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
      target: ng-runtime
      args:
        PROJECT: app-reservation
        CONFIG: development-docker
    image: ycyw/app-reservation:dev-docker
    environment:
      - APP_SUPPORT_URL=http://localhost:4203/remoteEntry.json
      - GATEWAY_URL=http://localhost:8080
    ports:
      - "4202:80"

  # Support
  app-support:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
      target: ng-runtime
      args:
        PROJECT: app-support
        CONFIG: development-docker
    image: ycyw/app-support:dev-docker
    environment:
      - GATEWAY_URL=http://localhost:8080
    ports:
      - "4203:80"
