# propriétés globales partagées à tous les services
config:
  loki:
    enabled: ${LOKI_ENABLED:true}
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

jwt:
  issuer: ${JWT_ISSUER:yc-cw}
  secret_key: ${JWT_SECRET_KEY:443a00f5072a066891ced7ea96f1926a1bcdb9f6d8ad4bbe3722cb59a2e15682}
  cookie:
    name: ${JWT_COOKIE_NAME:jwt}
  token:
    # Expiration time in seconds (default: 120s = 2 minutes)
    expiration: ${JWT_TOKEN_EXPIRATION:120}
  refresh:
    # Expiration time in seconds (default: 25200s = 7 hours)
    expiration: ${JWT_REFRESH_EXPIRATION:25200}

keystorage:
  revoked_token_prefix: ${KEYSTORAGE_REVOKED_TOKEN_PREFIX:revoked_token:}
  refresh_token_prefix: ${KEYSTORAGE_USER_REFRESH_TOKEN_PREFIX:refresh_token:}

server:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redispassword}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    com.ycyw: DEBUG

security:
  public-routes:
    - "/user-service-application/auth/login"
    - "/user-service-application/auth/register"
    - "/user-service-application/auth/refresh-token"
    - "/user-service-application/auth/logout"
    - "/user-service-application/v3/api-docs/**"
    - "/user-service-application/swagger-ui.html"
    - "/user-service-application/swagger-ui/**"
    - "/user-service-application/actuator/**"
    - "/support-service-application/v3/api-docs/**"
    - "/support-service-application/swagger-ui.html"
    - "/support-service-application/swagger-ui/**"
    - "/support-service-application/actuator/**"
