server:
  port: ${SUPPORT_SERVER_PORT}

debug: false

rabbitmq:
  chat:
    exchange: support-chat-exchange

spring:
  datasource:
    url: ${SUPPORT_DB_URL}
    username: ${SUPPORT_DB_USER}
    password: ${SUPPORT_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: ${SPDOC_ENABLE:false}
  swagger-ui:
    enabled: ${SPDOC_SWAGGER_ENABLE:false}
