server:
  port: ${SERVER_PORT}

debug: false

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false
  rabbitmq:
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
