server:
  port: ${USER_SERVER_PORT:8081}

debug: false

config:
  seed-data: true

spring:
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${USER_DB_USER:postgres}
    password: ${USER_DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  flyway:
    enabled: ${USER_DB_MIGRATE_ON_START:true}
    schemas: ${USER_DB_MIGRATION_SCHEMA:migrations}
    baseline-on-migrate: true # utile si la BDD existe déjà
    validate-on-migrate: true
  rabbitmq:
    username: ${USER_RABBIT_USER:guest}
    password: ${USER_RABBIT_PASSWORD:guest}
