server:
  port: ${USER_SERVER_PORT}

debug: false

spring:
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false
