[versions]
java = "21"
spring-boot = "3.4.4"
spring-cloud = "2024.0.2"
jspecify = "1.0.0"
error-prone = "2.29.2"
nullaway = "0.10.24"
errorprone-plugin = "4.1.0"
spotless = "6.25.0"
ktlint = "1.2.1"
google-java-format = "1.17.0"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
errorprone-core = { module = "com.google.errorprone:error-prone-core", version.ref = "error-prone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
postgresql = { module = "org.postgresql:postgresql" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
