server:
  port: 8761

spring:
  application:
    name: platform-service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

config:
  loki:
    url: http://localhost:3100/loki/api/v1/push

management:
  endpoints:
    web:
      exposure:
        include: health,info
