name: Gradle CI
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (Spotless + Checkstyle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - name: Run Spotless Check
        run: |
          cd backend
          ./gradlew spotlessCheck --no-daemon
      - name: Run Checkstyle
        run: |
          cd backend
          ./gradlew checkstyleMain checkstyleTest --no-daemon

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - name: Build
        run: |
          cd backend
          ./gradlew -Pnullaway=true build --scan --no-daemon
