server:
  port: ${GATEWAY_SERVER_PORT:8080}

spring:
  application:
    name: platform-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

config:
  loki:
    enabled: ${LOKI_ENABLED:true}
    url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

management:
  endpoints:
    web:
      exposure:
        include: health,info
