name: Build Backend

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-platform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      fail-fast: false
      matrix:
        module: ["config-server", "gateway", "service-registry"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build ${{ matrix.module }}
        run: ./gradlew :platform-${{ matrix.module }}:build -Pnullaway=true --scan --no-daemon

      - name: Upload ${{ matrix.module }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-back-platform-${{ matrix.module }}
          path: backend/platform/platform-${{ matrix.module }}/build/libs/

  build-services:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: support-service-application
            modulePath: services/support-service/support-service-application
          - module: user-service-application
            modulePath: services/user-service/user-service-application

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:build -Pnullaway=true --scan --no-daemon

      - name: Upload ${{ matrix.module }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-back-services-${{ matrix.module }}
          path: backend/services/${{ matrix.modulePath }}/build/libs/
