name: Front Images - Build & Push

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: "Le tag à utiliser pour l'image Docker (ex: 1.0.0, sha, etc.)"

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO: p13-poc-your-car-your-way

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: shell
            type: frontend
            project: shell
          - name: app-backoffice
            type: frontend
            project: app-backoffice
          - name: app-reservation
            type: frontend
            project: app-reservation
          - name: app-support
            type: frontend
            project: app-support

    concurrency:
      group: front-images-${{ matrix.name }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image tag
        id: meta
        shell: bash
        run: |
          OWNER_SAFE=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_BASE=${{ env.REGISTRY }}/${OWNER_SAFE}/${{ env.REPO }}-${{ matrix.name }}
          echo "tags=${IMAGE_BASE}:${{ inputs.tag }}" >> "$GITHUB_OUTPUT"

      # Phase 1: Build only (populate cache)
      - name: Build frontend (cache only)
        if: matrix.type == 'frontend'
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.front
          target: ng-runtime
          push: false
          build-args: |
            PROJECT=${{ matrix.project }}
            CONFIG=production
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      # Phase 2: Reuse cache and push
      - name: Push frontend image (reuse cache)
        if: matrix.type == 'frontend'
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.front
          target: ng-runtime
          push: true
          build-args: |
            PROJECT=${{ matrix.project }}
            CONFIG=production
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
