name: Lint & Check Backend

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck --no-daemon

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon
